Repository insightsengineering/teal.modules.clinical, pull requests merged in 2022-09, with the labels that each got.

#582 Update tm_t_binary_outcome.R
  NEWS.md
  R/tm_g_forest_rsp.R
  R/tm_t_binary_outcome.R
Labels: core, sme

#594 588 Add "Stratified by" Subtitles
  NEWS.md
  R/tm_g_forest_tte.R
  R/tm_t_binary_outcome.R
  R/tm_t_coxreg.R
  man/template_coxreg_u.Rd
  tests/testthat/test-tm_g_forest_tte.R
  tests/testthat/test-tm_t_binary_outcome.R
Labels: sme

#606 590 Fix typo in `tm_t_exposure` footnote
  R/tm_t_exposure.R
  tests/testthat/test-tm_t_exposure.R
Labels: sme

#605 592 Add visit subtitle to `tm_g_ci`
  NEWS.md
  R/tm_g_ci.R
Labels: sme

#600 fixes after changes in teal.code
  R/tm_g_barchart_simple.R
  R/tm_g_ci.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_ipp.R
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_patient_timeline.R
  R/tm_g_pp_therapy.R
  R/tm_g_pp_vitals.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_ancova.R
  R/tm_t_binary_outcome.R
  R/tm_t_coxreg.R
  R/tm_t_events.R
  R/tm_t_events_by_grade.R
  R/tm_t_events_patyear.R
  R/tm_t_logistic.R
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
  R/tm_t_pp_prior_medication.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_shift_by_grade.R
  R/tm_t_smq.R
Labels: core

#604 593 Fix `tm_t_smq` card name
  NEWS.md
  R/tm_t_smq.R
Labels: sme

#607 591 Add `tm_t_exposure` title/subtitle
  NEWS.md
  R/tm_t_exposure.R
  tests/testthat/test-tm_t_exposure.R
Labels: sme

#608 595 Add titles/subtitles for worst flag variable
  NEWS.md
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_shift_by_grade.R
  man/tm_t_shift_by_arm_by_worst.Rd
  tests/testthat/test-tm_t_shift_by_arm_by_worst.R
  tests/testthat/test-tm_t_shift_by_grade.R
Labels: sme

#616 561 Add CI Method footnote to `tm_t_events_patyear`
  NEWS.md
  R/tm_t_events_patyear.R
  man/tm_t_events_patyear.Rd
  tests/testthat/test-tm_t_events_patyear.R
Labels: sme

#615 add footnote and update test files
  R/tm_t_coxreg.R
  R/tm_t_tte.R
  man/template_coxreg_m.Rd
  tests/testthat/test-tm_t_coxreg.R
  tests/testthat/test-tm_t_tte.R
Labels: sme

#602 fix package --as-cran
  R/arm_ref_comp.R
  R/tm_a_mmrm.R
  R/tm_g_barchart_simple.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_km.R
  R/tm_g_lineplot.R
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_patient_timeline.R
  R/tm_g_pp_therapy.R
  R/tm_g_pp_vitals.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_binary_outcome.R
  R/tm_t_coxreg.R
  R/tm_t_exposure.R
  R/tm_t_logistic.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
  R/tm_t_pp_prior_medication.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_shift_by_grade.R
  R/tm_t_smq.R
  R/tm_t_summary_by.R
  R/tm_t_tte.R
  R/utils.R
  README.md
  man/arm_ref_comp_observer.Rd
  man/call_concatenate.Rd
  man/template_binary_outcome.Rd
  man/tm_a_mmrm.Rd
  man/tm_g_barchart_simple.Rd
  man/tm_g_forest_rsp.Rd
  man/tm_g_forest_tte.Rd
  man/tm_g_km.Rd
  man/tm_g_lineplot.Rd
  man/tm_g_pp_adverse_events.Rd
  man/tm_g_pp_patient_timeline.Rd
  man/tm_g_pp_therapy.Rd
  man/tm_g_pp_vitals.Rd
  man/tm_t_abnormality.Rd
  man/tm_t_abnormality_by_worst_grade.Rd
  man/tm_t_binary_outcome.Rd
  man/tm_t_coxreg.Rd
  man/tm_t_exposure.Rd
  man/tm_t_logistic.Rd
  man/tm_t_pp_laboratory.Rd
  man/tm_t_pp_medical_history.Rd
  man/tm_t_pp_prior_medication.Rd
  man/tm_t_shift_by_arm.Rd
  man/tm_t_shift_by_arm_by_worst.Rd
  man/tm_t_shift_by_grade.Rd
  man/tm_t_smq.Rd
  man/tm_t_summary_by.Rd
  man/tm_t_tte.Rd
Labels: core

#620 614 Add subtitle/footnotes to `tm_g_km`
  NEWS.md
  R/tm_g_km.R
  tests/testthat/test-tm_g_km.R
Labels: sme

#624 586 Add Stratified Newcombe to Stratified Analysis CI Method Options for `tm_t_binary_oucome`
  NEWS.md
  R/tm_t_binary_outcome.R
Labels: sme
