Repository insightsengineering/teal.modules.clinical, pull requests merged in 2022-07, with the labels that each got.

#518 init reporter tmc
  DESCRIPTION
  NEWS.md
  R/tm_a_mmrm.R
  R/tm_g_km.R
  R/tm_t_events.R
  R/tm_t_summary.R
  R/tm_t_tte.R
  staged_dependencies.yaml
Labels: core, sme

#529 fix tm_g_barchart
  R/tm_g_barchart_simple.R
  R/tm_t_shift_by_grade.R
Labels: bug, core

#531 DESC and README
  DESCRIPTION
  README.md
Labels: core

#530 527 Update to use `nestcolor::color_palette`
  DESCRIPTION
  NEWS.md
  R/tm_g_pp_vitals.R
  staged_dependencies.yaml
Labels: sme

#528 teal.reporter all modules
  DESCRIPTION
  NEWS.md
  R/arm_ref_comp.R
  R/tm_a_mmrm.R
  R/tm_g_barchart_simple.R
  R/tm_g_ci.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_ipp.R
  R/tm_g_km.R
  R/tm_g_lineplot.R
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_patient_timeline.R
  R/tm_g_pp_therapy.R
  R/tm_g_pp_vitals.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_ancova.R
  R/tm_t_binary_outcome.R
  R/tm_t_coxreg.R
  R/tm_t_events.R
  R/tm_t_events_by_grade.R
  R/tm_t_events_patyear.R
  R/tm_t_events_summary.R
  R/tm_t_exposure.R
  R/tm_t_logistic.R
  R/tm_t_mult_events.R
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
  R/tm_t_pp_prior_medication.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_shift_by_grade.R
  R/tm_t_smq.R
  R/tm_t_summary.R
  R/tm_t_summary_by.R
  R/tm_t_tte.R
  man/arm_ref_comp_observer.Rd
  man/tm_t_shift_by_arm_by_worst.Rd
  man/tm_t_smq.Rd
  tests/testthat/test-tm_t_pp_medical_history.R
Labels: core, sme, priority

#534 511 Implement `nestcolor` in TMC
  DESCRIPTION
  NEWS.md
  R/tm_g_barchart_simple.R
  R/tm_g_ci.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_ipp.R
  R/tm_g_km.R
  R/tm_g_lineplot.R
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_patient_timeline.R
  R/tm_g_pp_therapy.R
  R/tm_g_pp_vitals.R
  man/tm_g_barchart_simple.Rd
  man/tm_g_ci.Rd
  man/tm_g_forest_rsp.Rd
  man/tm_g_forest_tte.Rd
  man/tm_g_ipp.Rd
  man/tm_g_km.Rd
  man/tm_g_lineplot.Rd
  man/tm_g_pp_adverse_events.Rd
  man/tm_g_pp_patient_timeline.Rd
  man/tm_g_pp_therapy.Rd
  man/tm_g_pp_vitals.Rd
  vignettes/teal-modules-clinical.Rmd
Labels: enhancement, sme

#536 remove _FILTERED
  R/tm_g_forest_rsp.R
  R/tm_t_ancova.R
  R/tm_t_tte.R
  man/template_ancova.Rd
  man/template_forest_rsp.Rd
  man/template_tte.Rd
Labels: core

#537 reporter cleaning
  R/tm_a_mmrm.R
  R/tm_g_barchart_simple.R
  R/tm_g_ci.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_ipp.R
  R/tm_g_km.R
  R/tm_g_lineplot.R
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_patient_timeline.R
  R/tm_g_pp_therapy.R
  R/tm_g_pp_vitals.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_ancova.R
  R/tm_t_binary_outcome.R
  R/tm_t_coxreg.R
  R/tm_t_events.R
  R/tm_t_events_by_grade.R
  R/tm_t_events_patyear.R
  R/tm_t_events_summary.R
  R/tm_t_exposure.R
  R/tm_t_logistic.R
  R/tm_t_mult_events.R
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
  R/tm_t_pp_prior_medication.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_shift_by_grade.R
  R/tm_t_smq.R
  R/tm_t_summary.R
  R/tm_t_summary_by.R
  R/tm_t_tte.R
Labels: core

#538 rm inline - css tmc
  R/tm_a_mmrm.R
  R/tm_g_barchart_simple.R
  R/tm_g_km.R
  R/tm_t_coxreg.R
  R/tm_t_logistic.R
  R/tm_t_tte.R
  inst/css/custom.css
Labels: core, sme
