Repository insightsengineering/teal.modules.clinical, pull requests merged in 2022-11, with the labels that each got.

#671 consistent reactives naming
  R/tm_a_mmrm.R
  R/tm_g_barchart_simple.R
  R/tm_g_ci.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_ipp.R
  R/tm_g_km.R
  R/tm_g_lineplot.R
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_patient_timeline.R
  R/tm_g_pp_therapy.R
  R/tm_g_pp_vitals.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_ancova.R
  R/tm_t_binary_outcome.R
  R/tm_t_coxreg.R
  R/tm_t_events.R
  R/tm_t_events_by_grade.R
  R/tm_t_events_patyear.R
  R/tm_t_events_summary.R
  R/tm_t_exposure.R
  R/tm_t_logistic.R
  R/tm_t_mult_events.R
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
  R/tm_t_pp_prior_medication.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_shift_by_grade.R
  R/tm_t_smq.R
  R/tm_t_summary.R
  R/tm_t_summary_by.R
  R/tm_t_tte.R
  man/tm_t_shift_by_grade.Rd
Labels: core

#684 Update staged_dependencies.yaml, adding tern.gee
  DESCRIPTION
  staged_dependencies.yaml
Labels: sme

#689 Update tm_a_gee
  R/tm_a_gee.R
  man/template_a_gee.Rd
  man/tm_a_gee.Rd
Labels: core, sme

#674 423 Add interaction to `tm_t_ancova`
  NEWS.md
  R/argument_convention.R
  R/tm_t_ancova.R
  man/module_arguments.Rd
  man/template_ancova.Rd
  man/template_arguments.Rd
  man/tm_t_ancova.Rd
  tests/testthat/test-tm_t_ancova.R
Labels: sme

#690 679 Add tests for `tm_a_gee`
  R/tm_a_gee.R
  tests/testthat/test-tm_a_gee.R
Labels: sme

#692 Update line to produce output.
  R/tm_t_binary_outcome.R
Labels: sme

#691 681 Add titles/footnotes for `tm_a_gee`
  NEWS.md
  R/tm_a_gee.R
  man/template_a_gee.Rd
  man/tm_a_gee.Rd
Labels: sme

#693 685 Update description after release tag added
  DESCRIPTION
Labels: sme

#695 fix gee coefficient display
  R/tm_a_gee.R
Labels: sme

#664 add gee prototype module with example
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/teal.modules.clinical.R
  R/tm_a_gee.R
  inst/WORDLIST
  man/template_a_gee.Rd
  man/tm_a_gee.Rd
  tests/testthat/test-tm_a_gee.R
Labels: sme
