Repository insightsengineering/teal.modules.clinical, pull requests merged in 2022-10, with the labels that each got.

#626 Fix `tm_t_tte`, `tm_t_coxreg` footnotes
  R/tm_t_coxreg.R
  R/tm_t_tte.R
  tests/testthat/test-tm_t_coxreg.R
  tests/testthat/test-tm_t_tte.R
Labels: sme

#627 622 Clean up `teal.modules.clinical` NEWS
  NEWS.md
Labels: sme

#631 update title
  R/tm_t_summary.R
Labels: core

#632 Fix grammar in NEWS.md
  NEWS.md
Labels: sme

#646 633 Fix `tm_t_abnormality` footer
  R/tm_t_abnormality.R
  tests/testthat/test-tm_t_abnormality.R
Labels: sme

#649 Add validation for `tm_a_mmrm` covariate/visit conflict
  NEWS.md
  R/tm_a_mmrm.R
Labels: sme

#651 update roxygen for SRC
  R/tm_t_ancova.R
  R/tm_t_events_by_grade.R
  R/tm_t_events_patyear.R
  R/tm_t_summary_by.R
  man/tm_t_ancova.Rd
  man/tm_t_events_by_grade.Rd
  man/tm_t_events_patyear.Rd
  man/tm_t_summary_by.Rd
Labels: core

#647 525: parse cor_struct choices from tern.mmrm package
  R/tm_a_mmrm.R
Labels: sme, priority

#654 652 Fix TMC footnotes
  NEWS.md
  R/tm_g_km.R
  R/tm_t_coxreg.R
  R/tm_t_tte.R
  tests/testthat/test-tm_g_km.R
  tests/testthat/test-tm_t_tte.R
Labels: sme

#663 Use scda.2022
  DESCRIPTION
  NEWS.md
  staged_dependencies.yaml
Labels: core, sme, blocked

#621 qenv warnings
  R/tm_a_mmrm.R
  R/tm_g_barchart_simple.R
  R/tm_g_ci.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_ipp.R
  R/tm_g_km.R
  R/tm_g_lineplot.R
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_patient_timeline.R
  R/tm_g_pp_therapy.R
  R/tm_g_pp_vitals.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_ancova.R
  R/tm_t_binary_outcome.R
  R/tm_t_coxreg.R
  R/tm_t_events.R
  R/tm_t_events_by_grade.R
  R/tm_t_events_patyear.R
  R/tm_t_events_summary.R
  R/tm_t_exposure.R
  R/tm_t_logistic.R
  R/tm_t_mult_events.R
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
  R/tm_t_pp_prior_medication.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_shift_by_grade.R
  R/tm_t_smq.R
  R/tm_t_summary.R
  R/tm_t_summary_by.R
  R/tm_t_tte.R
Labels: core
