Repository insightsengineering/teal.modules.clinical, pull requests merged in 2022-12, with the labels that each got.

#697 696 Add table titles to `tm_a_gee` report cards
  R/tm_a_gee.R
Labels: sme

#701 summary modules
  R/tm_t_summary.R
  R/tm_t_summary_by.R
Labels: core

#704 mb tmc shinyvalidate
  R/tm_t_pp_prior_medication.R
Labels: core

#705 Validate modules
  R/tm_g_forest_rsp.R
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_patient_timeline.R
  R/tm_t_binary_outcome.R
  R/tm_t_mult_events.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
Labels: core

#703 contribution AC
  R/arm_ref_comp.R
  R/tm_g_barchart_simple.R
  R/tm_g_forest_rsp.R
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_patient_timeline.R
  R/tm_g_pp_therapy.R
  R/tm_g_pp_vitals.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_ancova.R
  R/tm_t_binary_outcome.R
  R/tm_t_exposure.R
  R/tm_t_logistic.R
  R/tm_t_mult_events.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
  man/arm_ref_comp_observer.Rd
  man/tm_t_abnormality_by_worst_grade.Rd
Labels: core

#713 tmg_g_pp_vitals: remove param
  DESCRIPTION
  NEWS.md
  R/tm_g_pp_vitals.R
  man/tm_g_pp_vitals.Rd
Labels: core, sme
