Repository insightsengineering/teal.modules.clinical, pull requests merged in 2023-11, with the labels that each got.

#852 chasing deprecations
  DESCRIPTION
  R/tm_a_gee.R
  R/tm_a_mmrm.R
  R/tm_g_barchart_simple.R
  R/tm_g_ci.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_ipp.R
  R/tm_g_km.R
  R/tm_g_lineplot.R
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_patient_timeline.R
  R/tm_g_pp_therapy.R
  R/tm_g_pp_vitals.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_ancova.R
  R/tm_t_binary_outcome.R
  R/tm_t_coxreg.R
  R/tm_t_events.R
  R/tm_t_events_by_grade.R
  R/tm_t_events_patyear.R
  R/tm_t_events_summary.R
  R/tm_t_exposure.R
  R/tm_t_logistic.R
  R/tm_t_mult_events.R
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
  R/tm_t_pp_prior_medication.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_shift_by_grade.R
  R/tm_t_smq.R
  R/tm_t_summary.R
  R/tm_t_summary_by.R
  R/tm_t_tte.R
  man/template_g_lineplot.Rd
  man/tm_g_lineplot.Rd
  man/tm_t_abnormality_by_worst_grade.Rd
  man/tm_t_exposure.Rd
  man/tm_t_shift_by_grade.Rd
Labels: core, sme

#857 `tdata` to `teal_data` - `tm_t_tte`
  R/tm_t_tte.R
Labels: core

#870 `tdata` to `teal_data` - `tm_t_mult_events`
  R/tm_t_mult_events.R
Labels: core

#858 `tdata` to `teal_data` - `tm_t_summary`
  R/tm_t_summary.R
Labels: core

#869 `tdata` to `teal_data` - `tm_t_pp_basic_info`
  R/tm_t_pp_basic_info.R
Labels: core

#868 `tdata` to `teal_data` - `tm_t_pp_laboratory`
  R/tm_t_pp_laboratory.R
Labels: core

#867 `tdata` to `teal_data` - `tm_t_pp_medical_history`
  R/tm_t_pp_medical_history.R
Labels: core

#866 `tdata` to `teal_data` - `tm_t_pp_prior_medication`
  R/tm_t_pp_prior_medication.R
Labels: core

#864 `tdata` to `teal_data` - `tm_t_shift_by_arm_by_worst`
  R/tm_t_shift_by_arm_by_worst.R
Labels: core

#856 `tdata` to `teal_data` - `tm_a_mmrm`
  R/tm_a_mmrm.R
Labels: core, refactor

#863 `tdata` to `teal_data` - `tm_t_shift_by_arm`
  R/tm_t_shift_by_arm.R
Labels: core

#862 `tdata` to `teal_data` - `tm_t_shift_by_grade`
  R/tm_t_shift_by_grade.R
Labels: core

#860 `tdata` to `teal_data` - `tm_t_smq`
  R/tm_t_smq.R
Labels: core

#859 `tdata` to `teal_data` - `tm_t_summary_by`
  R/tm_t_summary_by.R
Labels: core

#865 `tdata` to `teal_data` - `tm_g_barchart_simple`
  R/tm_g_barchart_simple.R
Labels: core

#875 `tdata` to `teal_data` - `tm_t_events_summary`
  R/tm_t_events_summary.R
Labels: core

#874 `tdata` to `teal_data` - `tm_t_events`
  R/tm_t_events.R
Labels: core

#871 `tdata` to `teal_data` - `tm_t_logistic`
  R/tm_t_logistic.R
Labels: core

#872 `tdata` to` teal_data` - `tm_t_exposure`
  R/tm_t_exposure.R
Labels: core

#873 `tdata` to `teal_data` - `tm_g_ci`
  R/tm_g_ci.R
Labels: core

#877 `tdata` to `teal_data` - `tm_t_events_by_grade`
  R/tm_t_events_by_grade.R
Labels: core

#885 `tdata` to `teal_data` - `tm_t_abnormality_by_worst_grade`
  R/tm_t_abnormality_by_worst_grade.R
Labels: core, refactor

#888 `tdata` to `teal_data` - `tm_t_abnormality`
  R/tm_t_abnormality.R
Labels: core, refactor

#889 `tdata` to `teal_data` - `tm_t_ancova`
  R/tm_t_ancova.R
Labels: core, refactor

#883 `tdata` to `teal_data` - `tm_g_lineplot`
  R/tm_g_lineplot.R
Labels: core

#887 `tdata` to `teal_data` - `tm_g_pp_therapy`
  R/tm_g_pp_therapy.R
Labels: core

#884 `tdata` to `teal_data` - `tm_g_pp_adverse_events`
  R/tm_g_pp_adverse_events.R
Labels: core

#879 `tdata` to `teal_data` - `tm_g_forest_rsp`
  R/tm_g_forest_rsp.R
Labels: core

#880 `tdata` to `teal_data` - `tm_g_forest_rsp`
  R/tm_g_forest_tte.R
Labels: core

#881 `tdata` to `teal_data` - `tm_g_forest_rsp`
  R/tm_g_ipp.R
Labels: core

#892 fix missing prefixes
  DESCRIPTION
  R/tm_a_gee.R
  R/tm_a_mmrm.R
  R/tm_g_barchart_simple.R
  R/tm_g_ci.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_events.R
  R/tm_t_events_by_grade.R
  R/tm_t_events_patyear.R
  R/tm_t_events_summary.R
  R/tm_t_exposure.R
  R/tm_t_logistic.R
  R/tm_t_mult_events.R
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
  R/tm_t_pp_prior_medication.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_shift_by_grade.R
  R/tm_t_smq.R
  R/tm_t_summary.R
  R/tm_t_summary_by.R
  R/tm_t_tte.R
Labels: core, refactor

#882 `tdata` to `teal_data` - `tm_g_km`
  R/tm_g_km.R
Labels: core

#893 `tdata` to` teal_data` - `tm_t_coxreg`
  R/tm_t_coxreg.R
Labels: core

#890 `tdata` to `teal_data` - `tm_t_binary_outcome`
  R/tm_t_binary_outcome.R
Labels: core, refactor

#894 `tdata` to `teal_data` - `tm_g_pp_vitals`
  R/tm_g_pp_vitals.R
Labels: core

#896 fix `tm_g_pp_vitals`
  DESCRIPTION
  NEWS.md
  R/tm_g_pp_vitals.R
Labels: core

#898 `get_code` to return concatenated code string
  R/tm_a_gee.R
  R/tm_a_mmrm.R
  R/tm_g_barchart_simple.R
  R/tm_g_ci.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_ipp.R
  R/tm_g_km.R
  R/tm_g_lineplot.R
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_patient_timeline.R
  R/tm_g_pp_therapy.R
  R/tm_g_pp_vitals.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_ancova.R
  R/tm_t_binary_outcome.R
  R/tm_t_coxreg.R
  R/tm_t_events.R
  R/tm_t_events_by_grade.R
  R/tm_t_events_patyear.R
  R/tm_t_events_summary.R
  R/tm_t_exposure.R
  R/tm_t_logistic.R
  R/tm_t_mult_events.R
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
  R/tm_t_pp_prior_medication.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_shift_by_grade.R
  R/tm_t_smq.R
  R/tm_t_summary.R
  R/tm_t_summary_by.R
  R/tm_t_tte.R
Labels: core
