Repository insightsengineering/teal.modules.clinical, pull requests merged in 2023-08, with the labels that each got.

#801 propagate argument name change in teal::module
  R/tm_a_gee.R
  R/tm_a_mmrm.R
  R/tm_g_barchart_simple.R
  R/tm_g_ci.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_ipp.R
  R/tm_g_km.R
  R/tm_g_lineplot.R
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_patient_timeline.R
  R/tm_g_pp_therapy.R
  R/tm_g_pp_vitals.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_ancova.R
  R/tm_t_binary_outcome.R
  R/tm_t_coxreg.R
  R/tm_t_events.R
  R/tm_t_events_by_grade.R
  R/tm_t_events_patyear.R
  R/tm_t_events_summary.R
  R/tm_t_exposure.R
  R/tm_t_logistic.R
  R/tm_t_mult_events.R
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
  R/tm_t_pp_prior_medication.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_shift_by_grade.R
  R/tm_t_smq.R
  R/tm_t_summary.R
  R/tm_t_summary_by.R
  R/tm_t_tte.R
Labels: core

#810 804 deprecation notes in `ggplot2`
  DESCRIPTION
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_therapy.R
  R/tm_g_pp_vitals.R
Labels: core

#808 Can't add reporter in patients timeline module
  R/tm_g_pp_patient_timeline.R
Labels: core

#812 Improve default annotation table sizing in `tm_g_km`
  NEWS.md
  R/tm_g_km.R
  man/template_g_km.Rd
Labels: core, sme

#814 803 page length
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_prior_medication.R
Labels: core

#818 update snapshot
  tests/testthat/_snaps/tm_g_km.md
Labels: bug, core, sme

#826 Refactor `tm_t_exposure` to remove summary row
  NEWS.md
  R/tm_t_exposure.R
  man/template_exposure.Rd
  man/tm_t_exposure.Rd
  tests/testthat/_snaps/tm_t_exposure.md
Labels: core, sme
