Repository insightsengineering/teal.modules.clinical, pull requests merged in 2023-12, with the labels that each got.

#901 Update `tern` version
  DESCRIPTION
Labels: core

#903 bump `teal.reporter` dep version
  DESCRIPTION
Labels: core

#899 Fix bug forcing `tm_g_lineplot` to initialize with a table
  NEWS.md
  R/tm_g_lineplot.R
  man/tm_g_lineplot.Rd
Labels: sme

#851 Add options to `tm_t_events` for sorting and overall rows
  NEWS.md
  R/tm_t_events.R
  man/template_events.Rd
  man/tm_t_events.Rd
  tests/testthat/_snaps/tm_t_events.md
Labels: sme

#905 Remove unused `table_names` argument from `surv_timepoint`
  R/tm_t_tte.R
  tests/testthat/_snaps/tm_t_tte.md
Labels: sme

#855 `tdata` to `teal_data`
  DESCRIPTION
  NEWS.md
  R/tm_a_gee.R
  R/tm_a_mmrm.R
  R/tm_g_barchart_simple.R
  R/tm_g_ci.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_ipp.R
  R/tm_g_km.R
  R/tm_g_lineplot.R
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_patient_timeline.R
  R/tm_g_pp_therapy.R
  R/tm_g_pp_vitals.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_ancova.R
  R/tm_t_binary_outcome.R
  R/tm_t_coxreg.R
  R/tm_t_events.R
  R/tm_t_events_by_grade.R
  R/tm_t_events_patyear.R
  R/tm_t_events_summary.R
  R/tm_t_exposure.R
  R/tm_t_logistic.R
  R/tm_t_mult_events.R
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
  R/tm_t_pp_prior_medication.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_shift_by_grade.R
  R/tm_t_smq.R
  R/tm_t_summary.R
  R/tm_t_summary_by.R
  R/tm_t_tte.R
  man/tm_a_gee.Rd
Labels: core, refactor

#909 fix resolve_delayed
  DESCRIPTION
  NAMESPACE
  R/teal.modules.clinical.R
Labels: core

#907 906 update dependency versions
  DESCRIPTION
Labels: core

#914 231 remove get_labels function
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_therapy.R
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_prior_medication.R
Labels: core
