Repository insightsengineering/teal.modules.clinical, pull requests merged in 2023-03, with the labels that each got.

#731 Add TMC example data
  NEWS.md
  R/data.R
  R/labels.R
  R/tm_a_gee.R
  R/tm_a_mmrm.R
  R/tm_g_lineplot.R
  R/tm_g_pp_vitals.R
  R/tm_t_ancova.R
  R/tm_t_events_patyear.R
  R/tm_t_exposure.R
  R/tm_t_pp_medical_history.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  data/tmc_ex_adae.rda
  data/tmc_ex_adaette.rda
  data/tmc_ex_adcm.rda
  data/tmc_ex_adeg.rda
  data/tmc_ex_adex.rda
  data/tmc_ex_adlb.rda
  data/tmc_ex_admh.rda
  data/tmc_ex_adqs.rda
  data/tmc_ex_adrs.rda
  data/tmc_ex_adsl.rda
  data/tmc_ex_adtte.rda
  data/tmc_ex_advs.rda
  inst/WORDLIST
  man/column_annotation_label.Rd
  man/ex_data.Rd
  man/template_g_km.Rd
  man/template_g_lineplot.Rd
  man/tm_a_gee.Rd
  man/tm_a_mmrm.Rd
  man/tm_g_lineplot.Rd
  man/tm_g_pp_vitals.Rd
  man/tm_t_ancova.Rd
  man/tm_t_events_patyear.Rd
  man/tm_t_exposure.Rd
  man/tm_t_pp_medical_history.Rd
  man/tm_t_shift_by_arm.Rd
  man/tm_t_shift_by_arm_by_worst.Rd
  vignettes/generate_tmc_test_data.Rmd
Labels: sme, automation

#736 Consistent lowercase dataset names in examples
  R/tm_g_barchart_simple.R
  R/tm_g_ci.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_km.R
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_therapy.R
  R/tm_t_binary_outcome.R
  R/tm_t_coxreg.R
  R/tm_t_events_summary.R
  R/tm_t_logistic.R
  R/tm_t_mult_events.R
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_prior_medication.R
  R/tm_t_tte.R
  R/validate_standard_inputs.R
  man/tm_g_barchart_simple.Rd
  man/tm_g_ci.Rd
  man/tm_g_forest_rsp.Rd
  man/tm_g_forest_tte.Rd
  man/tm_g_km.Rd
  man/tm_g_pp_adverse_events.Rd
  man/tm_g_pp_therapy.Rd
  man/tm_t_binary_outcome.Rd
  man/tm_t_coxreg.Rd
  man/tm_t_events_summary.Rd
  man/tm_t_logistic.Rd
  man/tm_t_mult_events.Rd
  man/tm_t_pp_basic_info.Rd
  man/tm_t_pp_laboratory.Rd
  man/tm_t_pp_prior_medication.Rd
  man/tm_t_tte.Rd
  man/validate_standard_inputs.Rd
  vignettes/teal-modules-clinical.Rmd
Labels: sme

#734 Remove `scda` and `scda.2022` from staged deps
  staged_dependencies.yaml
Labels: sme

#737 adding two mo correlation struct, close #716
  R/tm_a_gee.R
Labels: sme

#739 Clean up example data modification
  R/tm_g_barchart_simple.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_ipp.R
  R/tm_g_km.R
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_patient_timeline.R
  R/tm_g_pp_therapy.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_ancova.R
  R/tm_t_binary_outcome.R
  R/tm_t_coxreg.R
  R/tm_t_events.R
  R/tm_t_events_by_grade.R
  R/tm_t_events_summary.R
  R/tm_t_logistic.R
  R/tm_t_mult_events.R
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
  R/tm_t_pp_prior_medication.R
  R/tm_t_smq.R
  R/tm_t_summary_by.R
  R/tm_t_tte.R
  R/utils.R
  man/bracket_expr.Rd
  man/tm_g_barchart_simple.Rd
  man/tm_g_forest_rsp.Rd
  man/tm_g_forest_tte.Rd
  man/tm_g_ipp.Rd
  man/tm_g_km.Rd
  man/tm_g_pp_adverse_events.Rd
  man/tm_g_pp_patient_timeline.Rd
  man/tm_g_pp_therapy.Rd
  man/tm_t_abnormality.Rd
  man/tm_t_abnormality_by_worst_grade.Rd
  man/tm_t_ancova.Rd
  man/tm_t_binary_outcome.Rd
  man/tm_t_coxreg.Rd
  man/tm_t_events.Rd
  man/tm_t_events_by_grade.Rd
  man/tm_t_events_summary.Rd
  man/tm_t_logistic.Rd
  man/tm_t_mult_events.Rd
  man/tm_t_pp_basic_info.Rd
  man/tm_t_pp_laboratory.Rd
  man/tm_t_pp_medical_history.Rd
  man/tm_t_pp_prior_medication.Rd
  man/tm_t_smq.Rd
  man/tm_t_summary_by.Rd
  man/tm_t_tte.Rd
Labels: sme

#740 add teal.gallery to readme
  README.md
  inst/WORDLIST
Labels: core

#743 Fix `validate_standard_inputs` example
  R/validate_standard_inputs.R
  man/validate_standard_inputs.Rd
Labels: sme

#747 fix svg
  NEWS.md
  vignettes/quickstart_substitute.Rmd
Labels: bug, sme

#749 Add `lubridate` for ... date and time
  DESCRIPTION
  NEWS.md
  data/tmc_ex_adae.rda
  data/tmc_ex_adaette.rda
  data/tmc_ex_adcm.rda
  data/tmc_ex_adeg.rda
  data/tmc_ex_adex.rda
  data/tmc_ex_adlb.rda
  data/tmc_ex_admh.rda
  data/tmc_ex_adqs.rda
  data/tmc_ex_adrs.rda
  data/tmc_ex_adsl.rda
  data/tmc_ex_adtte.rda
  data/tmc_ex_advs.rda
  tests/testthat/_snaps/tm_t_summary.md
  vignettes/generate_tmc_test_data.Rmd
Labels: enhancement, sme
