Repository insightsengineering/teal.modules.clinical, pull requests merged in 2023-09, with the labels that each got.

#828 Patient Profile Modules only show relevant datanames
  NEWS.md
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_patient_timeline.R
  R/tm_g_pp_therapy.R
  R/tm_g_pp_vitals.R
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
  R/tm_t_pp_prior_medication.R
  R/tm_t_summary.R
Labels: core

#791 Solution for maintaining indent after pruning
  NEWS.md
  R/tm_t_events.R
  tests/testthat/_snaps/tm_t_events.md
Labels: sme

#833 Fix bug in `tm_t_coxreg` when no covariates selected
  NEWS.md
  R/tm_t_coxreg.R
  tests/testthat/_snaps/tm_t_coxreg.md
Labels: core, sme

#831 Fix `tm_t_coxreg` errors when applying filters
  NEWS.md
  R/arm_ref_comp.R
  R/tm_t_coxreg.R
  tests/testthat/_snaps/tm_t_coxreg.md
Labels: sme

#834 Display Patient ID in relevant templates, clean up data tables in reports
  DESCRIPTION
  NEWS.md
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_therapy.R
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
  man/template_basic_info.Rd
  man/template_laboratory.Rd
  man/template_medical_history.Rd
  staged_dependencies.yaml
  tests/testthat/_snaps/tm_t_pp_medical_history.md
Labels: sme

#836 Corrects linter errors detected on `198_card_labels@main`
  R/tm_a_mmrm.R
  R/tm_g_pp_patient_timeline.R
  R/tm_t_events.R
  R/tm_t_logistic.R
  R/tm_t_mult_events.R
  R/tm_t_tte.R
Labels: core
