Repository insightsengineering/teal.modules.clinical, pull requests merged in 2024-01, with the labels that each got.

#911 Update forest plots following refactor of `g_forest`
  DESCRIPTION
  NEWS.md
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  man/template_forest_rsp.Rd
  man/template_forest_tte.Rd
  man/tm_g_forest_rsp.Rd
  man/tm_g_forest_tte.Rd
  tests/testthat/_snaps/tm_g_forest_rsp.md
  tests/testthat/_snaps/tm_g_forest_tte.md
Labels: sme

#916 Two arm vars
  R/tm_t_summary.R
  R/tm_t_summary_by.R
  tests/testthat/_snaps/tm_t_summary.md
  tests/testthat/_snaps/tm_t_summary_by.md
Labels: core, sme

#922 Fix TMC to work with tern v0.9.3
  .github/workflows/check.yaml
  .github/workflows/docs.yaml
  DESCRIPTION
  NEWS.md
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  man/template_forest_rsp.Rd
  man/template_forest_tte.Rd
  man/tm_g_forest_rsp.Rd
  man/tm_g_forest_tte.Rd
  tests/testthat/_snaps/tm_g_forest_rsp.md
  tests/testthat/_snaps/tm_g_forest_tte.md
Labels: sme

#936 430 use `expect_no_error` in tests instead of `expect_error(, NA)`
  DESCRIPTION
  man/teal.modules.clinical.Rd
  tests/testthat/test-string_ops.R
  tests/testthat/test-substitute_names.R
  tests/testthat/test-validate_standard_inputs.R
Labels: core

#927 919 update vignettes@main
  R/utils.R
  inst/WORDLIST
  man/clean_description.Rd
  vignettes/quickstart_substitute.Rmd
  vignettes/teal-modules-clinical.Rmd
Labels: documentation, sme

#942 Add `default_total_label` function
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/tm_a_mmrm.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_binary_outcome.R
  R/tm_t_events.R
  R/tm_t_events_by_grade.R
  R/tm_t_events_patyear.R
  R/tm_t_events_summary.R
  R/tm_t_exposure.R
  R/tm_t_mult_events.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_shift_by_grade.R
  R/tm_t_smq.R
  R/tm_t_summary.R
  R/tm_t_summary_by.R
  R/tm_t_tte.R
  R/utils.R
  _pkgdown.yml
  inst/WORDLIST
  man/default_total_label.Rd
  man/template_abnormality.Rd
  man/template_abnormality_by_worst_grade.Rd
  man/template_binary_outcome.Rd
  man/template_events.Rd
  man/template_events_by_grade.Rd
  man/template_events_col_by_grade.Rd
  man/template_events_patyear.Rd
  man/template_events_summary.Rd
  man/template_fit_mmrm.Rd
  man/template_mult_events.Rd
  man/template_shift_by_arm.Rd
  man/template_shift_by_arm_by_worst.Rd
  man/template_shift_by_grade.Rd
  man/template_smq.Rd
  man/template_summary.Rd
  man/template_summary_by.Rd
  man/template_tte.Rd
  man/tm_a_mmrm.Rd
  man/tm_t_abnormality.Rd
  man/tm_t_abnormality_by_worst_grade.Rd
  man/tm_t_binary_outcome.Rd
  man/tm_t_events.Rd
  man/tm_t_events_by_grade.Rd
  man/tm_t_events_patyear.Rd
  man/tm_t_events_summary.Rd
  man/tm_t_exposure.Rd
  man/tm_t_mult_events.Rd
  man/tm_t_shift_by_arm.Rd
  man/tm_t_shift_by_arm_by_worst.Rd
  man/tm_t_shift_by_grade.Rd
  man/tm_t_smq.Rd
  man/tm_t_summary.Rd
  man/tm_t_summary_by.Rd
  man/tm_t_tte.Rd
  tests/testthat/test-utils.R
Labels: sme

#982 918 update teal.modules.clinical.R with `#' @keywords internal "_PACKAGE"`
  R/teal.modules.clinical.R
Labels: core

#926 TMC bug fixes
  DESCRIPTION
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_logistic.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  man/tm_t_abnormality.Rd
  man/tm_t_abnormality_by_worst_grade.Rd
  man/tm_t_shift_by_arm.Rd
  man/tm_t_shift_by_arm_by_worst.Rd
Labels: core

#939 Replace `aval` parameter with `aval_var`
  NEWS.md
  R/argument_convention.R
  R/teal.modules.clinical.R
  R/tm_g_pp_vitals.R
  R/tm_t_pp_laboratory.R
  man/module_arguments.Rd
  man/teal.modules.clinical.Rd
  man/template_a_gee.Rd
  man/template_ancova.Rd
  man/template_arguments.Rd
  man/template_binary_outcome.Rd
  man/template_coxreg_m.Rd
  man/template_coxreg_u.Rd
  man/template_events_patyear.Rd
  man/template_exposure.Rd
  man/template_fit_mmrm.Rd
  man/template_forest_rsp.Rd
  man/template_forest_tte.Rd
  man/template_g_ipp.Rd
  man/template_g_km.Rd
  man/template_laboratory.Rd
  man/template_logistic.Rd
  man/template_tte.Rd
  man/template_vitals.Rd
  man/tm_g_ipp.Rd
  man/tm_g_pp_vitals.Rd
  man/tm_t_pp_laboratory.Rd
  tests/testthat/test-tm_t_tte.R
Labels: sme

#940 Replace `avalu` parameter with `avalu_var`
  NEWS.md
  R/argument_convention.R
  R/tm_g_ipp.R
  R/tm_t_exposure.R
  R/tm_t_pp_laboratory.R
  man/module_arguments.Rd
  man/template_arguments.Rd
  man/template_exposure.Rd
  man/template_g_ipp.Rd
  man/template_laboratory.Rd
  man/tm_t_pp_laboratory.Rd
Labels: sme

#797 Adds min package version
  .github/workflows/scheduled.yaml
  DESCRIPTION
  NEWS.md
Labels: core

#941 Replace `base_var` parameter with `baseline_var`
  NEWS.md
  R/argument_convention.R
  R/tm_g_ipp.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  man/module_arguments.Rd
  man/template_arguments.Rd
  man/template_g_ipp.Rd
  man/template_shift_by_arm.Rd
  man/template_shift_by_arm_by_worst.Rd
  man/tm_g_ipp.Rd
  man/tm_t_shift_by_arm.Rd
  man/tm_t_shift_by_arm_by_worst.Rd
  tests/testthat/test-tm_g_ipp.R
  tests/testthat/test-tm_t_shift_by_arm.R
  tests/testthat/test-tm_t_shift_by_arm_by_worst.R
Labels: sme

#990 update deps of roxygenize hook
  .pre-commit-config.yaml
  DESCRIPTION
Labels: core

#993 Minor improvements to README/vignettes
  README.md
  inst/WORDLIST
  vignettes/teal-modules-clinical.Rmd
Labels: sme

#997 Clean up documentation for `tm_t_shift_by_arm_by_worst`
  R/argument_convention.R
  R/tm_t_shift_by_arm_by_worst.R
  man/module_arguments.Rd
  man/template_arguments.Rd
  man/template_shift_by_arm_by_worst.Rd
  man/tm_t_shift_by_arm_by_worst.Rd
Labels: sme

#998 Clean up documentation for `tm_t_shift_by_grade`
  R/tm_t_shift_by_grade.R
  man/template_shift_by_grade.Rd
  man/tm_t_shift_by_grade.Rd
Labels: sme
