Repository insightsengineering/teal.modules.clinical, pull requests merged in 2024-05, with the labels that each got.

#1137 Wave 2 - `tm_g_lineplot` shinytest2
  tests/testthat/test-shinytest2-tm_g_lineplot.R
Labels: core

#1138 Wave 2 - `tm_g_forest_tte` shinytest2
  tests/testthat/test-shinytest2-tm_g_forest_tte.R
Labels: core

#1174 Wave 7 - `tm_t_tte` shinytests
  tests/testthat/test-shinytest2-tm_t_tte.R
Labels: core

#1173 Wave 7 - `tm_t_summary_by` shinytests
  tests/testthat/test-shinytest2-tm_t_summary_by.R
Labels: core

#1172 Wave 7 - `tm_t_summary` shinytests
  tests/testthat/test-shinytest2-tm_t_summary.R
Labels: core

#1171 Wave 7 - `tm_t_smq` shinytests
  tests/testthat/test-shinytest2-tm_t_smq.R
Labels: core

#1170 Wave 7 - `tm_t_shift_by_grade` shinytests
  tests/testthat/test-shinytest2-tm_t_shift_by_grade.R
Labels: core

#1169 Wave 7 - `tm_t_shift_by_arm_by_worst` shinytests
  tests/testthat/test-shinytest2-tm_t_shift_by_arm_by_worst.R
Labels: core

#1143 Wave 3 - `tm_g_pp_vitals` shinytest2
  tests/testthat/test-shinytest2-tm_g_pp_vitals.R
Labels: core

#1144 Wave 3 - `tm_t_abnormality` shinytest2
  tests/testthat/test-shinytest2-tm_t_abnormality.R
Labels: core

#1131 Wave 1 - `tm_a_mmrm` shinytests
  tests/testthat/test-shinytest2-tm_a_mmrm.R
Labels: core

#1164 Wave 6 - `tm_t_pp_basic_info` shinytests
  tests/testthat/test-shinytest2-tm_t_pp_basic_info.R
Labels: core

#1165 Wave 6 - `tm_t_pp_laboratory` shinytests
  tests/testthat/test-shinytest2-tm_t_pp_laboratory.R
Labels: core

#1166 Wave 6 - `tm_t_pp_medical_history` shinytests
  tests/testthat/test-shinytest2-tm_t_pp_medical_history.R
Labels: core

#1167 Wave 6 - `tm_t_pp_prior_medication` shinytests
  tests/testthat/test-shinytest2-tm_t_pp_prior_medication.R
Labels: core

#1168 Wave 6 - `tm_t_shift_by_arm` shinytests
  tests/testthat/test-shinytest2-tm_t_shift_by_arm.R
Labels: core

#1146 Wave 3 - `tm_g_pp_patient_timeline` shinytest2
  tests/testthat/test-shinytest2-tm_g_pp_patient_timeline.R
Labels: core

#1159 Wave 5 - `tm_t_events_patyear` shinytests
  tests/testthat/test-shinytest2-tm_t_events_patyear.R
Labels: core

#1160 Wave 5 - `tm_t_events_summary` shinytests
  tests/testthat/test-shinytest2-tm_t_events_summary.R
Labels: core

#1162 Wave 5 - `tm_t_logistic` shinytests
  tests/testthat/test-shinytest2-tm_t_logistic.R
Labels: core

#1163 Wave 5 - `tm_t_mult_events` shinytests
  tests/testthat/test-shinytest2-tm_t_mult_events.R
Labels: core

#1154 Wave 4 - `tm_t_ancova` shinytests
  tests/testthat/test-shinytest2-tm_t_ancova.R
Labels: core

#1155 Wave 4 - `tm_t_binary_outcome` shinytests
  tests/testthat/test-shinytest2-tm_t_binary_outcome.R
Labels: core

#1156 Wave 4 - `tm_t_coxreg` shinytests
  tests/testthat/test-shinytest2-tm_t_coxreg.R
Labels: core

#1157 Wave 4 - `tm_t_events` shinytests
  tests/testthat/test-shinytest2-tm_t_events.R
Labels: core

#1158 Wave 4 - `tm_t_events_by_grade` shinytests
  tests/testthat/test-shinytest2-tm_t_events_by_grade.R
Labels: core

#1150 Wave2 - `tm_g_pp_adverse_events` shinytests
  tests/testthat/test-shinytest2-tm_g_pp_adverse_events.R
Labels: core

#1145 Wave 3 - `tm_t_abnormality_by_worst_grade` shinytest2
  tests/testthat/test-shinytest2-tm_t_abnormality_by_worst_grade.R
Labels: core, blocked

#1148 Wave 3 - `tm_g_pp_therapy` shinytest2
  R/tm_g_pp_therapy.R
  tests/testthat/test-shinytest2-tm_g_pp_therapy.R
Labels: core

#1178 1175 fixing validation on `col_by_var` variable.
  R/tm_t_exposure.R
  man/template_exposure.Rd
Labels: core, sme

#1177 1149 introduce `ylim` parameter for `tm_g_km` module
  NEWS.md
  R/tm_g_km.R
  man/template_g_km.Rd
  tests/testthat/_snaps/tm_g_km.md
Labels: enhancement, core

#1161 Wave 5 - `tm_t_exposure` shinytests
  tests/testthat/test-shinytest2-tm_t_exposure.R
Labels: core

#1184 Post cleanup shinytest2
  tests/testthat/test-shinytest2-tm_a_gee.R
  tests/testthat/test-shinytest2-tm_a_mmrm.R
  tests/testthat/test-shinytest2-tm_g_barchart_simple.R
  tests/testthat/test-shinytest2-tm_g_ci.R
  tests/testthat/test-shinytest2-tm_g_forest_rsp.R
  tests/testthat/test-shinytest2-tm_g_forest_tte.R
  tests/testthat/test-shinytest2-tm_g_ipp.R
  tests/testthat/test-shinytest2-tm_g_km.R
  tests/testthat/test-shinytest2-tm_g_lineplot.R
  tests/testthat/test-shinytest2-tm_g_pp_adverse_events.R
  tests/testthat/test-shinytest2-tm_g_pp_patient_timeline.R
  tests/testthat/test-shinytest2-tm_g_pp_therapy.R
  tests/testthat/test-shinytest2-tm_g_pp_vitals.R
  tests/testthat/test-shinytest2-tm_t_abnormality.R
  tests/testthat/test-shinytest2-tm_t_abnormality_by_worst_grade.R
  tests/testthat/test-shinytest2-tm_t_ancova.R
  tests/testthat/test-shinytest2-tm_t_binary_outcome.R
  tests/testthat/test-shinytest2-tm_t_coxreg.R
  tests/testthat/test-shinytest2-tm_t_events.R
  tests/testthat/test-shinytest2-tm_t_events_by_grade.R
  tests/testthat/test-shinytest2-tm_t_events_patyear.R
  tests/testthat/test-shinytest2-tm_t_events_summary.R
  tests/testthat/test-shinytest2-tm_t_exposure.R
  tests/testthat/test-shinytest2-tm_t_logistic.R
  tests/testthat/test-shinytest2-tm_t_mult_events.R
  tests/testthat/test-shinytest2-tm_t_pp_basic_info.R
  tests/testthat/test-shinytest2-tm_t_pp_laboratory.R
  tests/testthat/test-shinytest2-tm_t_pp_medical_history.R
  tests/testthat/test-shinytest2-tm_t_pp_prior_medication.R
  tests/testthat/test-shinytest2-tm_t_shift_by_arm.R
  tests/testthat/test-shinytest2-tm_t_shift_by_arm_by_worst.R
  tests/testthat/test-shinytest2-tm_t_shift_by_grade.R
  tests/testthat/test-shinytest2-tm_t_smq.R
  tests/testthat/test-shinytest2-tm_t_summary.R
  tests/testthat/test-shinytest2-tm_t_summary_by.R
  tests/testthat/test-shinytest2-tm_t_tte.R
Labels: core

#1126 1108 `{shinytest2}` feature branch
  .github/workflows/check.yaml
  DESCRIPTION
  R/tm_a_gee.R
  R/tm_g_pp_therapy.R
  tests/testthat/helper-TealAppDriver.R
  tests/testthat/test-shinytest2-tm_a_gee.R
  tests/testthat/test-shinytest2-tm_a_mmrm.R
  tests/testthat/test-shinytest2-tm_g_barchart_simple.R
  tests/testthat/test-shinytest2-tm_g_ci.R
  tests/testthat/test-shinytest2-tm_g_forest_rsp.R
  tests/testthat/test-shinytest2-tm_g_forest_tte.R
  tests/testthat/test-shinytest2-tm_g_ipp.R
  tests/testthat/test-shinytest2-tm_g_km.R
  tests/testthat/test-shinytest2-tm_g_lineplot.R
  tests/testthat/test-shinytest2-tm_g_pp_adverse_events.R
  tests/testthat/test-shinytest2-tm_g_pp_patient_timeline.R
  tests/testthat/test-shinytest2-tm_g_pp_therapy.R
  tests/testthat/test-shinytest2-tm_g_pp_vitals.R
  tests/testthat/test-shinytest2-tm_t_abnormality.R
  tests/testthat/test-shinytest2-tm_t_abnormality_by_worst_grade.R
  tests/testthat/test-shinytest2-tm_t_ancova.R
  tests/testthat/test-shinytest2-tm_t_binary_outcome.R
  tests/testthat/test-shinytest2-tm_t_coxreg.R
  tests/testthat/test-shinytest2-tm_t_events.R
  tests/testthat/test-shinytest2-tm_t_events_by_grade.R
  tests/testthat/test-shinytest2-tm_t_events_patyear.R
  tests/testthat/test-shinytest2-tm_t_events_summary.R
  tests/testthat/test-shinytest2-tm_t_exposure.R
  tests/testthat/test-shinytest2-tm_t_logistic.R
  tests/testthat/test-shinytest2-tm_t_mult_events.R
  tests/testthat/test-shinytest2-tm_t_pp_basic_info.R
  tests/testthat/test-shinytest2-tm_t_pp_laboratory.R
  tests/testthat/test-shinytest2-tm_t_pp_medical_history.R
  tests/testthat/test-shinytest2-tm_t_pp_prior_medication.R
  tests/testthat/test-shinytest2-tm_t_shift_by_arm.R
  tests/testthat/test-shinytest2-tm_t_shift_by_arm_by_worst.R
  tests/testthat/test-shinytest2-tm_t_shift_by_grade.R
  tests/testthat/test-shinytest2-tm_t_smq.R
  tests/testthat/test-shinytest2-tm_t_summary.R
  tests/testthat/test-shinytest2-tm_t_summary_by.R
  tests/testthat/test-shinytest2-tm_t_tte.R
Labels: core

#1180 1176 remove `Show Warnings` from modules
  NEWS.md
  R/tm_a_gee.R
  R/tm_a_mmrm.R
  R/tm_g_barchart_simple.R
  R/tm_g_ci.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_ipp.R
  R/tm_g_km.R
  R/tm_g_lineplot.R
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_patient_timeline.R
  R/tm_g_pp_therapy.R
  R/tm_g_pp_vitals.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_ancova.R
  R/tm_t_binary_outcome.R
  R/tm_t_coxreg.R
  R/tm_t_events.R
  R/tm_t_events_by_grade.R
  R/tm_t_events_patyear.R
  R/tm_t_events_summary.R
  R/tm_t_exposure.R
  R/tm_t_logistic.R
  R/tm_t_mult_events.R
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
  R/tm_t_pp_prior_medication.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_shift_by_grade.R
  R/tm_t_smq.R
  R/tm_t_summary.R
  R/tm_t_summary_by.R
  R/tm_t_tte.R
Labels: core

#1182 227 utilize `logger::log_shiny_input_change`
  DESCRIPTION
  NEWS.md
  R/tm_a_gee.R
  R/tm_a_mmrm.R
  R/tm_g_barchart_simple.R
  R/tm_g_ci.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_ipp.R
  R/tm_g_km.R
  R/tm_g_lineplot.R
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_patient_timeline.R
  R/tm_g_pp_therapy.R
  R/tm_g_pp_vitals.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_ancova.R
  R/tm_t_binary_outcome.R
  R/tm_t_coxreg.R
  R/tm_t_events.R
  R/tm_t_events_by_grade.R
  R/tm_t_events_patyear.R
  R/tm_t_events_summary.R
  R/tm_t_exposure.R
  R/tm_t_logistic.R
  R/tm_t_mult_events.R
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
  R/tm_t_pp_prior_medication.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_shift_by_grade.R
  R/tm_t_smq.R
  R/tm_t_summary.R
  R/tm_t_summary_by.R
  R/tm_t_tte.R
  man/template_g_km.Rd
Labels: core
