Repository insightsengineering/teal.modules.clinical, pull requests merged in 2024-11, with the labels that each got.

#1238 Adds `roxy.shinylive` to pre-commit configuration
  .pre-commit-config.yaml
Labels: core

#1251 1248 Fix shinytest2 tests
  R/tm_a_gee.R
  R/tm_a_mmrm.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_ipp.R
  R/tm_g_km.R
  R/tm_g_lineplot.R
  R/tm_g_pp_therapy.R
  R/tm_g_pp_vitals.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_ancova.R
  R/tm_t_binary_outcome.R
  R/tm_t_events.R
  R/tm_t_events_by_grade.R
  R/tm_t_events_patyear.R
  R/tm_t_events_summary.R
  R/tm_t_exposure.R
  R/tm_t_mult_events.R
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_medical_history.R
  R/tm_t_pp_prior_medication.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_shift_by_grade.R
  R/tm_t_smq.R
  R/tm_t_summary.R
  R/tm_t_summary_by.R
  R/tm_t_tte.R
  tests/testthat/test-shinytest2-tm_g_pp_therapy.R
Labels: core

#1246 update `strata` var to `group_var`
  R/tm_g_lineplot.R
  man/template_g_lineplot.Rd
  man/tm_g_lineplot.Rd
  tests/testthat/test-shinytest2-tm_g_lineplot.R
  tests/testthat/test-tm_g_lineplot.R
Labels: sme

#1265 introduce decorators for `tm_g_ci`
  R/tm_g_ci.R
Labels: core

#1264 introduce decorators for `tm_g_forest_tte`
  R/tm_g_forest_tte.R
Labels: core

#1262 introduce decorators for `tm_a_gee`
  R/tm_a_gee.R
Labels: core

#1263 introduce decorators for `tm_g_ipp`
  R/tm_g_ipp.R
Labels: core

#1270 introduce decorators to `tm_g_pp_patient_timeline`
  R/tm_g_pp_patient_timeline.R
Labels: core

#1271 Bring back tests for `tm_g_pp_therapy`
  R/tm_g_pp_therapy.R
  tests/testthat/test-shinytest2-tm_g_pp_therapy.R
Labels: bug, core

#1268 introduce decorators for `tm_g_pp_therapy`
  R/tm_g_pp_therapy.R
Labels: core

#1261 introduce decorators for `tm_g_pp_vitals`
  R/tm_g_pp_vitals.R
Labels: core

#1257 introduce decorators for `tm_t_abnormality`
  R/tm_t_abnormality.R
  man/tm_t_abnormality.Rd
Labels: core

#1254 Introduce decorators for `tm_g_km`
  R/tm_g_km.R
  man/tm_g_km.Rd
Labels: core

#1255 Introduce decorators for `tm_g_lineplot`
  R/tm_g_lineplot.R
  man/tm_g_lineplot.Rd
Labels: core

#1256 introduce decorators for `tm_t_ancova`
  R/tm_t_ancova.R
Labels: core

#1260 introduce decorators for `tm_t_abnormality_by_worst_grade`
  R/tm_t_abnormality_by_worst_grade.R
Labels: core
