Repository insightsengineering/teal.modules.clinical, pull requests merged in 2024-02, with the labels that each got.

#1008 Update DESCRIPTION teal.data (>= 0.4.0)
  DESCRIPTION
Labels: sme, priority

#1006 Consolidate argument_convention file
  R/argument_convention.R
  R/tm_a_gee.R
  R/tm_a_mmrm.R
  R/tm_g_barchart_simple.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_km.R
  R/tm_g_lineplot.R
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_patient_timeline.R
  R/tm_g_pp_therapy.R
  R/tm_g_pp_vitals.R
  R/tm_t_ancova.R
  R/tm_t_binary_outcome.R
  R/tm_t_coxreg.R
  R/tm_t_events_patyear.R
  R/tm_t_events_summary.R
  R/tm_t_logistic.R
  R/tm_t_pp_basic_info.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
  R/tm_t_pp_prior_medication.R
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_shift_by_grade.R
  R/tm_t_summary.R
  R/tm_t_tte.R
  man/make_barchart_simple_call.Rd
  man/module_arguments.Rd
  man/template_abnormality.Rd
  man/template_abnormality_by_worst_grade.Rd
  man/template_arguments.Rd
  man/template_binary_outcome.Rd
  man/template_events.Rd
  man/template_events_by_grade.Rd
  man/template_events_col_by_grade.Rd
  man/template_events_patyear.Rd
  man/template_events_summary.Rd
  man/template_exposure.Rd
  man/template_fit_mmrm.Rd
  man/template_mult_events.Rd
  man/template_shift_by_arm.Rd
  man/template_shift_by_arm_by_worst.Rd
  man/template_shift_by_grade.Rd
  man/template_smq.Rd
  man/template_summary.Rd
  man/template_summary_by.Rd
  man/template_tte.Rd
  man/tm_g_barchart_simple.Rd
  man/tm_g_ci.Rd
  man/tm_g_forest_rsp.Rd
  man/tm_g_forest_tte.Rd
  man/tm_g_lineplot.Rd
  man/tm_g_pp_adverse_events.Rd
  man/tm_g_pp_patient_timeline.Rd
  man/tm_g_pp_therapy.Rd
  man/tm_g_pp_vitals.Rd
  man/tm_t_summary.Rd
  man/tm_t_summary_by.Rd
Labels: sme, priority

#981 618 reduce dependencies of the package
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/facet_grid_formula.R
  R/teal.modules.clinical.R
  R/tm_t_events.R
  R/tm_t_events_summary.R
  R/tm_t_pp_laboratory.R
  R/utils.R
  _pkgdown.yml
  man/styled_expr.Rd
  vignettes/quickstart_substitute.Rmd
Labels: core

#994 Clean up documentation for `tm_t_binary_outcome`
  R/argument_convention.R
  R/tm_t_binary_outcome.R
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_shift_by_grade.R
  man/module_arguments.Rd
  man/template_arguments.Rd
  man/template_binary_outcome.Rd
  man/template_shift_by_arm_by_worst.Rd
  man/template_shift_by_grade.Rd
  man/tm_t_binary_outcome.Rd
  man/tm_t_shift_by_arm_by_worst.Rd
  man/tm_t_shift_by_grade.Rd
Labels: sme

#1003 Clean up documentation for `tm_t_summary_by`
  R/argument_convention.R
  R/tm_t_summary_by.R
  man/module_arguments.Rd
  man/prepare_arm_levels.Rd
  man/template_abnormality.Rd
  man/template_abnormality_by_worst_grade.Rd
  man/template_arguments.Rd
  man/template_events.Rd
  man/template_events_by_grade.Rd
  man/template_events_col_by_grade.Rd
  man/template_events_patyear.Rd
  man/template_mult_events.Rd
  man/template_shift_by_grade.Rd
  man/template_smq.Rd
  man/template_summary.Rd
  man/template_summary_by.Rd
  man/tm_t_abnormality.Rd
  man/tm_t_abnormality_by_worst_grade.Rd
  man/tm_t_events.Rd
  man/tm_t_events_by_grade.Rd
  man/tm_t_events_patyear.Rd
  man/tm_t_mult_events.Rd
  man/tm_t_shift_by_grade.Rd
  man/tm_t_smq.Rd
  man/tm_t_summary_by.Rd
Labels: core, sme

#1004 Clean up documentation for `tm_t_summary`
  R/tm_t_summary.R
  man/template_summary.Rd
  man/tm_t_summary.Rd
Labels: core, sme

#1026 Clean up documentation for `tm_g_pp_adverse_events`
  R/argument_convention.R
  R/tm_g_pp_adverse_events.R
  man/module_arguments.Rd
  man/template_adverse_events.Rd
  man/template_arguments.Rd
  man/template_g_km.Rd
  man/tm_g_pp_adverse_events.Rd
Labels: core, sme

#1023 Clean up documentation for `tm_t_pp_prior_medication`
  R/argument_convention.R
  R/tm_t_pp_prior_medication.R
  man/module_arguments.Rd
  man/template_arguments.Rd
  man/template_prior_medication.Rd
  man/tm_t_pp_prior_medication.Rd
Labels: core, sme

#1022 Clean up documentation for `tm_t_pp_medical_history`
  R/tm_t_pp_medical_history.R
  man/template_medical_history.Rd
  man/tm_t_pp_medical_history.Rd
Labels: core, sme

#1020 Clean up documentation for `tm_g_forest_rsp`
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  man/template_forest_rsp.Rd
  man/template_forest_tte.Rd
  man/tm_g_forest_rsp.Rd
  tests/testthat/_snaps/tm_g_forest_rsp.md
Labels: core, sme

#1025 Clean up documentation for `tm_g_pp_therapy`
  R/argument_convention.R
  R/tm_g_pp_therapy.R
  man/template_therapy.Rd
  man/tm_g_pp_therapy.Rd
Labels: core, sme

#1015 Clean up documentation for `tm_t_events_summary`
  R/tm_t_events_summary.R
  inst/WORDLIST
  man/template_events_summary.Rd
  man/tm_t_events_summary.Rd
Labels: core, sme

#1019 Clean up documentation for `tm_t_mult_events`
  R/argument_convention.R
  R/tm_t_mult_events.R
  man/template_arguments.Rd
  man/template_mult_events.Rd
  man/tm_t_mult_events.Rd
Labels: core, sme

#1011 Clean up documentation for `tm_t_tte`
  R/tm_t_tte.R
  man/control_tte.Rd
  man/template_tte.Rd
  man/tm_t_tte.Rd
Labels: core, sme

#1016 clean up documentation for `tm_t_ancova`
  R/argument_convention.R
  R/tm_t_ancova.R
  man/template_ancova.Rd
  man/template_arguments.Rd
  man/tm_t_ancova.Rd
  tests/testthat/_snaps/tm_t_events.md
  tests/testthat/_snaps/tm_t_events_summary.md
Labels: core, sme

#1018 Clean up documentation for `tm_t_smq`
  R/argument_convention.R
  R/tm_t_smq.R
  inst/WORDLIST
  man/template_arguments.Rd
  man/template_smq.Rd
  man/tm_t_smq.Rd
Labels: core, sme

#1029 clean up documentation for tm_t_abnormality_by_worst_grade
  R/tm_t_abnormality_by_worst_grade.R
  man/template_abnormality_by_worst_grade.Rd
  man/tm_t_abnormality_by_worst_grade.Rd
Labels: core, sme

#1027 clean up tm_t_abnormality documentation
  R/tm_t_abnormality.R
  man/template_abnormality.Rd
  man/tm_t_abnormality.Rd
Labels: core, sme

#1031 Clean up documentation for `tm_t_shift_by_arm`
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  man/template_shift_by_arm.Rd
  man/template_shift_by_arm_by_worst.Rd
  man/tm_t_shift_by_arm.Rd
Labels: sme

#1030 Clean up `tm_g_km` documentation
  R/tm_g_km.R
  man/template_g_km.Rd
  man/tm_g_km.Rd
Labels: sme

#1032 Clean up documentation for `tm_t_events_patyear`
  R/argument_convention.R
  R/tm_g_ipp.R
  R/tm_t_binary_outcome.R
  R/tm_t_events_patyear.R
  R/tm_t_exposure.R
  man/module_arguments.Rd
  man/template_arguments.Rd
  man/template_events_patyear.Rd
  man/tm_g_ipp.Rd
  man/tm_t_events_patyear.Rd
  man/tm_t_exposure.Rd
Labels: sme

#1021 Clean up documentation for `tm_g_forest_tte`
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  man/template_forest_tte.Rd
  man/tm_g_forest_tte.Rd
Labels: core, sme

#996 Clean up documentation for `tm_g_lineplot`
  R/tm_g_lineplot.R
  man/template_g_lineplot.Rd
  man/tm_g_lineplot.Rd
Labels: core, sme

#995 Clean up documentation for `tm_t_coxreg`
  R/tm_t_coxreg.R
  inst/WORDLIST
  man/template_coxreg_m.Rd
  man/template_coxreg_u.Rd
  man/tm_t_coxreg.Rd
  vignettes/teal-modules-clinical.Rmd
Labels: core, sme

#1033 Clean up documentation for `tm_g_barchart_simple`
  R/tm_g_barchart_simple.R
  man/make_barchart_simple_call.Rd
  man/tm_g_barchart_simple.Rd
Labels: sme

#1039 clean up documentation for `tm_t_events_by_grade`.
  R/argument_convention.R
  R/tm_t_events_by_grade.R
  man/template_arguments.Rd
  man/template_events_by_grade.Rd
  man/template_events_col_by_grade.Rd
  man/tm_t_events_by_grade.Rd
Labels: core, sme

#1007 Clean up documentation for `tm_t_logistic`
  R/tm_t_logistic.R
  man/template_logistic.Rd
  man/tm_t_logistic.Rd
  tests/testthat/test-tm_t_logisitic.R
Labels: core, sme

#1028 Clean up documentation for `tm_t_exposure()`
  R/argument_convention.R
  R/tm_t_exposure.R
  man/module_arguments.Rd
  man/template_exposure.Rd
  man/tm_a_gee.Rd
  man/tm_a_mmrm.Rd
  man/tm_g_ci.Rd
  man/tm_g_forest_rsp.Rd
  man/tm_g_forest_tte.Rd
  man/tm_g_ipp.Rd
  man/tm_g_km.Rd
  man/tm_g_lineplot.Rd
  man/tm_t_abnormality.Rd
  man/tm_t_abnormality_by_worst_grade.Rd
  man/tm_t_ancova.Rd
  man/tm_t_binary_outcome.Rd
  man/tm_t_coxreg.Rd
  man/tm_t_events.Rd
  man/tm_t_events_by_grade.Rd
  man/tm_t_events_patyear.Rd
  man/tm_t_events_summary.Rd
  man/tm_t_exposure.Rd
  man/tm_t_logistic.Rd
  man/tm_t_mult_events.Rd
  man/tm_t_shift_by_arm.Rd
  man/tm_t_shift_by_arm_by_worst.Rd
  man/tm_t_shift_by_grade.Rd
  man/tm_t_smq.Rd
  man/tm_t_summary.Rd
  man/tm_t_summary_by.Rd
  man/tm_t_tte.Rd
Labels: sme

#1040 944 clean tm a gee@main
  R/tm_a_gee.R
  man/template_a_gee.Rd
  man/tm_a_gee.Rd
Labels: core, sme

#1002 `tm_t_events` review
  R/argument_convention.R
  R/tm_t_events.R
  man/make_barchart_simple_call.Rd
  man/template_a_gee.Rd
  man/template_abnormality.Rd
  man/template_abnormality_by_worst_grade.Rd
  man/template_adverse_events.Rd
  man/template_ancova.Rd
  man/template_arguments.Rd
  man/template_binary_outcome.Rd
  man/template_coxreg_m.Rd
  man/template_coxreg_u.Rd
  man/template_events.Rd
  man/template_events_by_grade.Rd
  man/template_events_col_by_grade.Rd
  man/template_events_patyear.Rd
  man/template_exposure.Rd
  man/template_fit_mmrm.Rd
  man/template_forest_tte.Rd
  man/template_g_ci.Rd
  man/template_logistic.Rd
  man/template_mult_events.Rd
  man/template_patient_timeline.Rd
  man/template_shift_by_arm.Rd
  man/template_shift_by_arm_by_worst.Rd
  man/template_shift_by_grade.Rd
  man/template_smq.Rd
  man/template_summary.Rd
  man/template_summary_by.Rd
  man/template_therapy.Rd
  man/template_tte.Rd
  man/template_vitals.Rd
  man/tm_a_gee.Rd
  man/tm_a_mmrm.Rd
  man/tm_g_barchart_simple.Rd
  man/tm_g_ci.Rd
  man/tm_g_forest_tte.Rd
  man/tm_g_pp_adverse_events.Rd
  man/tm_g_pp_patient_timeline.Rd
  man/tm_g_pp_therapy.Rd
  man/tm_g_pp_vitals.Rd
  man/tm_t_abnormality.Rd
  man/tm_t_abnormality_by_worst_grade.Rd
  man/tm_t_ancova.Rd
  man/tm_t_binary_outcome.Rd
  man/tm_t_coxreg.Rd
  man/tm_t_events.Rd
  man/tm_t_events_by_grade.Rd
  man/tm_t_events_patyear.Rd
  man/tm_t_events_summary.Rd
  man/tm_t_exposure.Rd
  man/tm_t_logistic.Rd
  man/tm_t_mult_events.Rd
  man/tm_t_shift_by_arm.Rd
  man/tm_t_shift_by_arm_by_worst.Rd
  man/tm_t_shift_by_grade.Rd
  man/tm_t_smq.Rd
  man/tm_t_summary.Rd
  man/tm_t_summary_by.Rd
  man/tm_t_tte.Rd
Labels: documentation, core, sme

#1036 Clean up documentation for `tm_t_pp_laboratory`
  R/argument_convention.R
  R/tm_a_gee.R
  R/tm_g_barchart_simple.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_ipp.R
  R/tm_g_km.R
  R/tm_g_lineplot.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_ancova.R
  R/tm_t_binary_outcome.R
  R/tm_t_coxreg.R
  R/tm_t_events.R
  R/tm_t_events_by_grade.R
  R/tm_t_events_patyear.R
  R/tm_t_events_summary.R
  R/tm_t_exposure.R
  R/tm_t_logistic.R
  R/tm_t_mult_events.R
  R/tm_t_pp_laboratory.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_grade.R
  R/tm_t_smq.R
  R/tm_t_summary.R
  R/tm_t_summary_by.R
  R/tm_t_tte.R
  man/module_arguments.Rd
  man/template_abnormality_by_worst_grade.Rd
  man/template_arguments.Rd
  man/template_coxreg_m.Rd
  man/template_coxreg_u.Rd
  man/template_exposure.Rd
  man/template_fit_mmrm.Rd
  man/template_g_ipp.Rd
  man/template_laboratory.Rd
  man/template_shift_by_arm.Rd
  man/template_shift_by_arm_by_worst.Rd
  man/template_shift_by_grade.Rd
  man/tm_a_gee.Rd
  man/tm_a_mmrm.Rd
  man/tm_g_forest_rsp.Rd
  man/tm_g_forest_tte.Rd
  man/tm_g_ipp.Rd
  man/tm_g_km.Rd
  man/tm_g_lineplot.Rd
  man/tm_t_abnormality.Rd
  man/tm_t_abnormality_by_worst_grade.Rd
  man/tm_t_ancova.Rd
  man/tm_t_binary_outcome.Rd
  man/tm_t_coxreg.Rd
  man/tm_t_events_patyear.Rd
  man/tm_t_exposure.Rd
  man/tm_t_logistic.Rd
  man/tm_t_pp_laboratory.Rd
  man/tm_t_shift_by_arm.Rd
  man/tm_t_shift_by_arm_by_worst.Rd
  man/tm_t_shift_by_grade.Rd
  man/tm_t_summary_by.Rd
  man/tm_t_tte.Rd
Labels: sme

#1038 Clean up documentation for `tm_g_pp_patient_timeline`
  R/tm_g_pp_patient_timeline.R
  man/template_patient_timeline.Rd
  man/tm_g_pp_patient_timeline.Rd
Labels: sme

#1035 Clean up documentation for `tm_g_ci`
  R/tm_g_ci.R
  man/template_g_ci.Rd
  man/tm_g_ci.Rd
Labels: sme

#1041 clean up documentation for `tm_a_mmrm`
  R/tm_a_mmrm.R
  man/template_fit_mmrm.Rd
  man/tm_a_mmrm.Rd
Labels: core, sme

#1046 1012 substitute `{assertthat}` with `{checkmate}` in a couple of functions
  .pre-commit-config.yaml
  DESCRIPTION
  NAMESPACE
  R/dynamic_assertions.R
  R/facet_grid_formula.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_ipp.R
  R/tm_g_km.R
  R/tm_g_lineplot.R
  R/tm_g_pp_adverse_events.R
  R/tm_g_pp_patient_timeline.R
  R/tm_g_pp_therapy.R
  R/tm_g_pp_vitals.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_ancova.R
  R/tm_t_binary_outcome.R
  R/tm_t_events.R
  R/tm_t_events_by_grade.R
  R/tm_t_events_summary.R
  R/tm_t_exposure.R
  R/tm_t_logistic.R
  R/tm_t_mult_events.R
  R/tm_t_pp_laboratory.R
  R/tm_t_pp_medical_history.R
  R/tm_t_pp_prior_medication.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_shift_by_grade.R
  R/tm_t_smq.R
  R/tm_t_summary.R
  R/tm_t_summary_by.R
  R/tm_t_tte.R
  R/utils.R
  man/dyn_assertion.Rd
Labels: core

#1049 Fix pkgdown redirect
  DESCRIPTION
  man/teal.modules.clinical.Rd
Labels: bug, core

#1054 Update DESCRIPTION teal 0.15.0
  DESCRIPTION
Labels: core, sme

#1051 removing internal functions example.
  NAMESPACE
  R/arm_ref_comp.R
  R/facet_grid_formula.R
  R/string_ops.R
  R/substitute_names.R
  R/validate_standard_inputs.R
  _pkgdown.yml
  man/arm_ref_comp_observer.Rd
  man/as_num.Rd
  man/facet_grid_formula.Rd
  man/substitute_names.Rd
  man/substitute_q.Rd
  man/validate_standard_inputs.Rd
Labels: core

#1056 Append the teal.transform namespace to stay consistent
  R/argument_convention.R
  R/tm_t_tte.R
  man/module_arguments.Rd
  man/tm_a_gee.Rd
  man/tm_a_mmrm.Rd
  man/tm_g_forest_rsp.Rd
  man/tm_g_forest_tte.Rd
  man/tm_g_km.Rd
  man/tm_t_abnormality.Rd
  man/tm_t_abnormality_by_worst_grade.Rd
  man/tm_t_ancova.Rd
  man/tm_t_binary_outcome.Rd
  man/tm_t_coxreg.Rd
  man/tm_t_events.Rd
  man/tm_t_events_by_grade.Rd
  man/tm_t_events_patyear.Rd
  man/tm_t_events_summary.Rd
  man/tm_t_mult_events.Rd
  man/tm_t_shift_by_arm.Rd
  man/tm_t_shift_by_arm_by_worst.Rd
  man/tm_t_shift_by_grade.Rd
  man/tm_t_smq.Rd
  man/tm_t_summary.Rd
  man/tm_t_summary_by.Rd
  man/tm_t_tte.Rd
Labels: documentation, sme

#1045 Check description and vignette
  DESCRIPTION
  vignettes/quickstart_substitute.Rmd
  vignettes/teal-modules-clinical.Rmd
Labels: sme

#1067 Fix assertion on paramcd
  R/tm_t_shift_by_arm.R
Labels: bug, core

#1059 Clarify `tm_g_pp_patient_timeline` error message
  R/tm_g_pp_patient_timeline.R
Labels: core, sme

#1069 Update DESCRIPTION teal.transform >= 0.5.0
  DESCRIPTION
Labels: core, sme

#1072 1071 prerelease cleanup@main
  .Rbuildignore
  .github/CONTRIBUTING.md
  DESCRIPTION
  R/teal.modules.clinical.R
  R/tm_t_coxreg.R
  README.md
  man/teal.modules.clinical.Rd
  man/tm_t_coxreg.Rd
Labels: core

#1075 Add missing return values
  R/utils.R
  man/bracket_expr.Rd
  man/call_concatenate.Rd
  man/clean_description.Rd
  man/color_lab_values.Rd
  man/extract_input.Rd
  man/pipe_expr.Rd
  man/prepare_arm.Rd
  man/prepare_arm_levels.Rd
  man/split_choices.Rd
  man/split_col_expr.Rd
  man/split_interactions.Rd
Labels: sme

#1070 Cran release 0.9.0 [skip vbump]
  DESCRIPTION
  NEWS.md
  man/teal.modules.clinical.Rd
Labels: sme

#1079 1077 remove `formatters`
  .pre-commit-config.yaml
  DESCRIPTION
  NEWS.md
  R/tm_g_barchart_simple.R
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_pp_patient_timeline.R
  R/tm_t_abnormality.R
  R/tm_t_abnormality_by_worst_grade.R
  R/tm_t_ancova.R
  R/tm_t_binary_outcome.R
  R/tm_t_events.R
  R/tm_t_events_by_grade.R
  R/tm_t_events_summary.R
  R/tm_t_exposure.R
  R/tm_t_logistic.R
  R/tm_t_mult_events.R
  R/tm_t_pp_medical_history.R
  R/tm_t_shift_by_grade.R
  R/tm_t_smq.R
  R/tm_t_summary.R
  R/tm_t_summary_by.R
  R/utils.R
  data/tmc_ex_adae.rda
  data/tmc_ex_adaette.rda
  data/tmc_ex_adcm.rda
  data/tmc_ex_adeg.rda
  data/tmc_ex_adex.rda
  data/tmc_ex_adlb.rda
  data/tmc_ex_admh.rda
  data/tmc_ex_adqs.rda
  data/tmc_ex_adrs.rda
  data/tmc_ex_adsl.rda
  data/tmc_ex_adtte.rda
  data/tmc_ex_advs.rda
  man/tm_g_barchart_simple.Rd
  man/tm_g_forest_rsp.Rd
  man/tm_g_forest_tte.Rd
  man/tm_g_pp_patient_timeline.Rd
  man/tm_t_abnormality.Rd
  man/tm_t_abnormality_by_worst_grade.Rd
  man/tm_t_binary_outcome.Rd
  man/tm_t_events_by_grade.Rd
  man/tm_t_events_summary.Rd
  man/tm_t_exposure.Rd
  staged_dependencies.yaml
  tests/testthat/_snaps/tm_t_abnormality.md
  tests/testthat/_snaps/tm_t_abnormality_by_worst_grade.md
  tests/testthat/_snaps/tm_t_ancova.md
  tests/testthat/_snaps/tm_t_events.md
  tests/testthat/_snaps/tm_t_events_by_grade.md
  tests/testthat/_snaps/tm_t_events_summary.md
  tests/testthat/_snaps/tm_t_exposure.md
  tests/testthat/_snaps/tm_t_logisitic.md
  tests/testthat/_snaps/tm_t_mult_events.md
  tests/testthat/_snaps/tm_t_pp_medical_history.md
  tests/testthat/_snaps/tm_t_shift_by_grade.md
  tests/testthat/_snaps/tm_t_smq.md
  tests/testthat/_snaps/tm_t_summary_by.md
  vignettes/generate_tmc_test_data.Rmd
Labels: core, sme

#925 Re-add `g_forest` updates
  DESCRIPTION
  NEWS.md
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  man/template_forest_rsp.Rd
  man/template_forest_tte.Rd
  man/tm_g_forest_rsp.Rd
  man/tm_g_forest_tte.Rd
  tests/testthat/_snaps/tm_g_forest_rsp.md
  tests/testthat/_snaps/tm_g_forest_tte.md
Labels: sme

#1083 Allow `NULL` `paramcd` value in `tm_t_summary_by`
  NEWS.md
  R/tm_t_summary_by.R
Labels: sme

#1088 Replace instances of deprecated `na_level` with `na_str`
  NEWS.md
  R/tm_t_abnormality.R
  R/tm_t_shift_by_arm.R
  R/tm_t_shift_by_arm_by_worst.R
  R/tm_t_summary.R
  R/tm_t_summary_by.R
Labels: sme

#1081 Update use of deprecated `strat` argument from `tern`
  NEWS.md
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/tm_g_km.R
  R/tm_t_tte.R
  R/utils.R
  man/add_expr.Rd
  man/h_concat_expr.Rd
  tests/testthat/_snaps/tm_g_forest_rsp.md
  tests/testthat/_snaps/tm_g_forest_tte.md
  tests/testthat/_snaps/utils.md
  tests/testthat/test-utils.R
Labels: sme

#985 Strict tests
  .pre-commit-config.yaml
  DESCRIPTION
  NEWS.md
  R/labels.R
  R/teal.modules.clinical.R
  R/tm_t_binary_outcome.R
  R/tm_t_events_summary.R
  man/column_annotation_label.Rd
  man/teal.modules.clinical-package.Rd
  man/tm_t_binary_outcome.Rd
  man/tm_t_events_summary.Rd
  tests/testthat/_snaps/tm_t_abnormality.md
  tests/testthat/_snaps/tm_t_shift_by_arm.md
  tests/testthat/_snaps/tm_t_shift_by_arm_by_worst.md
  tests/testthat/_snaps/tm_t_summary.md
  tests/testthat/_snaps/tm_t_summary_by.md
  tests/testthat/setup-logger.R
  tests/testthat/setup-options.R
  tests/testthat/test-tm_a_mmrm.R
  tests/testthat/test-tm_t_coxreg.R
  tests/testthat/test-tm_t_mult_events.R
  tests/testthat/test-tm_t_tte.R
  vignettes/generate_tmc_test_data.Rmd
  vignettes/quickstart_substitute.Rmd
  vignettes/teal-modules-clinical.Rmd
Labels: sme
