Repository insightsengineering/teal.modules.clinical, pull requests merged in 2025-02, with the labels that each got.

#1327 Make sure the code chunks does not break because of warnings
  vignettes/teal-modules-clinical.Rmd
Labels: core

#1328 vbump teal.widgets
  DESCRIPTION
Labels: core

#1325 Duplicated decorators during an edge case of named and unnamed decorators
  R/utils.R
Labels: core

#1334 Add `title_text` argument to `tm_t_mult_events()` to control dynamic title
  NEWS.md
  R/tm_t_mult_events.R
  man/tm_t_mult_events.Rd
  teal.modules.clinical.Rproj
  tests/testthat/test-shinytest2-tm_t_mult_events.R
Labels: sme

#1336 update tm_g_forest_tte
  NEWS.md
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  R/utils.R
Labels: core, sme

#1341 vbump teal.transform
  DESCRIPTION
Labels: core

#1345 Add treatment var levels assertion to `tm_t_events_summary()`
  NEWS.md
  R/tm_t_events_summary.R
  man/tm_a_gee.Rd
  man/tm_a_mmrm.Rd
  man/tm_g_barchart_simple.Rd
  man/tm_g_ci.Rd
  man/tm_g_forest_rsp.Rd
  man/tm_g_forest_tte.Rd
  man/tm_g_ipp.Rd
  man/tm_g_km.Rd
  man/tm_g_lineplot.Rd
  man/tm_g_pp_adverse_events.Rd
  man/tm_g_pp_patient_timeline.Rd
  man/tm_g_pp_therapy.Rd
  man/tm_g_pp_vitals.Rd
  man/tm_t_abnormality.Rd
  man/tm_t_abnormality_by_worst_grade.Rd
  man/tm_t_ancova.Rd
  man/tm_t_binary_outcome.Rd
  man/tm_t_coxreg.Rd
  man/tm_t_events.Rd
  man/tm_t_events_by_grade.Rd
  man/tm_t_events_patyear.Rd
  man/tm_t_events_summary.Rd
  man/tm_t_exposure.Rd
  man/tm_t_logistic.Rd
  man/tm_t_mult_events.Rd
  man/tm_t_pp_basic_info.Rd
  man/tm_t_pp_laboratory.Rd
  man/tm_t_pp_medical_history.Rd
  man/tm_t_pp_prior_medication.Rd
  man/tm_t_shift_by_arm.Rd
  man/tm_t_shift_by_arm_by_worst.Rd
  man/tm_t_shift_by_grade.Rd
  man/tm_t_smq.Rd
  man/tm_t_summary.Rd
  man/tm_t_summary_by.Rd
  man/tm_t_tte.Rd
Labels: sme

#1346 Update DESCRIPTION
  DESCRIPTION
  inst/WORDLIST
  man/teal.modules.clinical-package.Rd
Labels: core

#1347 Faster check times on CI
  .github/workflows/check.yaml
Labels: enhancement, core

#1351 fix: make sure the decoration is applied to the forest plots
  R/tm_g_forest_rsp.R
  R/tm_g_forest_tte.R
  man/template_forest_rsp.Rd
  man/template_forest_tte.Rd
  tests/testthat/_snaps/tm_g_forest_rsp.md
  tests/testthat/_snaps/tm_g_forest_tte.md
Labels: core

#1355 wrap within expr in {} to potentially cheat r cmd check
  R/tm_g_pp_adverse_events.R
  R/tm_t_events_by_grade.R
Labels: core

#1356 [skip vbump] upversion v0.10.0
  .github/workflows/scheduled.yaml
  DESCRIPTION
  NEWS.md
Labels: core
