Repository insightsengineering/teal.modules.clinical, pull requests merged in 2025-01, with the labels that each got.

#1308 upversion dep
  DESCRIPTION
Labels: sme

#1312 Fix logger
  DESCRIPTION
Labels: core

#1309 Show only datasets used
  R/tm_g_barchart_simple.R
  R/tm_g_ci.R
  R/utils.R
  man/normalize_decorators.Rd
  man/srv_decorate_teal_data.Rd
Labels: core

#1315 Update DESCRIPTION
  DESCRIPTION
Labels: core, sme

#1314 update packages for the scheduled build
  .github/workflows/scheduled.yaml
  DESCRIPTION
Labels: core

#1321 add Remotes to DESCRIPTION
  DESCRIPTION
Labels: core

#1318 simplify builds dependencies of extra-deps
  .github/workflows/scheduled.yaml
Labels: core

#1323 vbump teal.code
  DESCRIPTION
Labels: core

#1326 vbump teal.data
  .github/workflows/check.yaml
  .github/workflows/docs.yaml
  .github/workflows/release.yaml
  .github/workflows/scheduled.yaml
  DESCRIPTION
Labels: core
